# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'arena-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for arena-test
  pod 'Alamofire'
  pod 'Argo'
  pod 'Curry'
  pod 'PullToRefreshSwift'
  pod 'Kingfisher', '~> 3.0'
  
  target 'arena-testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'arena-testUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
